source 'http://rubygems.org'

gem 'chromedriver-helper'
gem 'cucumber', '3.1.2'
gem 'rspec', '3.8.0'
gem 'ffi', '1.9.25'
#gem 'watir-webdriver', '0.9.9'
gem 'watir'
gem 'selenium-webdriver'
gem 'headless', '2.3.1'
gem 'json', '2.1.0'
gem 'gherkin', '~> 5.1'
gem 'syntax'
